/**
 * MCC Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OrganizationUserProjectsInner } from './organizationUserProjectsInner';

export class OrganizationUser {
    'clientId'?: string;
    'createdAt'?: Date;
    /**
    * Name of the user
    */
    'name'?: string;
    /**
    * E-mail address of the user
    */
    'email': string;
    /**
    * Key of the organization
    */
    'organizationKey'?: string;
    /**
    * Name of the organization
    */
    'organizationName'?: string;
    'organizationScopes'?: Array<string>;
    'projects'?: Array<OrganizationUserProjectsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clientId",
            "baseName": "client_id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "organizationKey",
            "baseName": "organization_key",
            "type": "string"
        },
        {
            "name": "organizationName",
            "baseName": "organization_name",
            "type": "string"
        },
        {
            "name": "organizationScopes",
            "baseName": "organization_scopes",
            "type": "Array<string>"
        },
        {
            "name": "projects",
            "baseName": "projects",
            "type": "Array<OrganizationUserProjectsInner>"
        }    ];

    static getAttributeTypeMap() {
        return OrganizationUser.attributeTypeMap;
    }
}

