/* tslint:disable */
/* eslint-disable */
/**
 * MCC Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiClient
 */
export interface ApiClient {
    /**
     * 
     * @type {Date}
     * @memberof ApiClient
     */
    createdAt: Date;
    /**
     * description about the api client
     * @type {string}
     * @memberof ApiClient
     */
    description?: string;
    /**
     * the client id
     * @type {string}
     * @memberof ApiClient
     */
    clientId: string;
    /**
     * the client id
     * @type {string}
     * @memberof ApiClient
     */
    clientSecret: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiClient
     */
    lastUsedAt?: Date;
    /**
     * Scope
     * @type {Array<string>}
     * @memberof ApiClient
     */
    scope: Array<string>;
}

/**
 * Check if a given object implements the ApiClient interface.
 */
export function instanceOfApiClient(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "clientId" in value;
    isInstance = isInstance && "clientSecret" in value;
    isInstance = isInstance && "scope" in value;

    return isInstance;
}

export function ApiClientFromJSON(json: any): ApiClient {
    return ApiClientFromJSONTyped(json, false);
}

export function ApiClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiClient {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'clientId': json['client_id'],
        'clientSecret': json['client_secret'],
        'lastUsedAt': !exists(json, 'last_used_at') ? undefined : (new Date(json['last_used_at'])),
        'scope': json['scope'],
    };
}

export function ApiClientToJSON(value?: ApiClient | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': (value.createdAt.toISOString()),
        'description': value.description,
        'client_id': value.clientId,
        'client_secret': value.clientSecret,
        'last_used_at': value.lastUsedAt === undefined ? undefined : (value.lastUsedAt.toISOString()),
        'scope': value.scope,
    };
}

