/* tslint:disable */
/* eslint-disable */
/**
 * MCC Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiClientDraft
 */
export interface ApiClientDraft {
    /**
     * description about the api client
     * @type {string}
     * @memberof ApiClientDraft
     */
    description?: string;
    /**
     * Scope
     * @type {Array<string>}
     * @memberof ApiClientDraft
     */
    scope?: Array<string>;
}

/**
 * Check if a given object implements the ApiClientDraft interface.
 */
export function instanceOfApiClientDraft(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiClientDraftFromJSON(json: any): ApiClientDraft {
    return ApiClientDraftFromJSONTyped(json, false);
}

export function ApiClientDraftFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiClientDraft {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'scope': !exists(json, 'scope') ? undefined : json['scope'],
    };
}

export function ApiClientDraftToJSON(value?: ApiClientDraft | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'scope': value.scope,
    };
}

