/* tslint:disable */
/* eslint-disable */
/**
 * MACH composer Cloud (MCC) Public API
 * # Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.  All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html). 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: mach@labdigital.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiClientAllOf
 */
export interface ApiClientAllOf {
    /**
     * description about the api client
     * @type {string}
     * @memberof ApiClientAllOf
     */
    description?: string;
    /**
     * the client id
     * @type {string}
     * @memberof ApiClientAllOf
     */
    clientId: string;
    /**
     * the client id
     * @type {string}
     * @memberof ApiClientAllOf
     */
    clientSecret: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiClientAllOf
     */
    lastUsedAt?: Date;
    /**
     * Scope
     * @type {Array<string>}
     * @memberof ApiClientAllOf
     */
    scope: Array<string>;
}

/**
 * Check if a given object implements the ApiClientAllOf interface.
 */
export function instanceOfApiClientAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "clientId" in value;
    isInstance = isInstance && "clientSecret" in value;
    isInstance = isInstance && "scope" in value;

    return isInstance;
}

export function ApiClientAllOfFromJSON(json: any): ApiClientAllOf {
    return ApiClientAllOfFromJSONTyped(json, false);
}

export function ApiClientAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiClientAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'clientId': json['client_id'],
        'clientSecret': json['client_secret'],
        'lastUsedAt': !exists(json, 'last_used_at') ? undefined : (new Date(json['last_used_at'])),
        'scope': json['scope'],
    };
}

export function ApiClientAllOfToJSON(value?: ApiClientAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'client_id': value.clientId,
        'client_secret': value.clientSecret,
        'last_used_at': value.lastUsedAt === undefined ? undefined : (value.lastUsedAt.toISOString()),
        'scope': value.scope,
    };
}

