/* tslint:disable */
/* eslint-disable */
/**
 * MCC Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiClient } from './ApiClient';
import {
    ApiClientFromJSON,
    ApiClientFromJSONTyped,
    ApiClientToJSON,
} from './ApiClient';

/**
 * 
 * @export
 * @interface ApiClientPaginatorAllOf
 */
export interface ApiClientPaginatorAllOf {
    /**
     * 
     * @type {Array<ApiClient>}
     * @memberof ApiClientPaginatorAllOf
     */
    results?: Array<ApiClient>;
}

/**
 * Check if a given object implements the ApiClientPaginatorAllOf interface.
 */
export function instanceOfApiClientPaginatorAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiClientPaginatorAllOfFromJSON(json: any): ApiClientPaginatorAllOf {
    return ApiClientPaginatorAllOfFromJSONTyped(json, false);
}

export function ApiClientPaginatorAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiClientPaginatorAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(ApiClientFromJSON)),
    };
}

export function ApiClientPaginatorAllOfToJSON(value?: ApiClientPaginatorAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(ApiClientToJSON)),
    };
}

