/* tslint:disable */
/* eslint-disable */
/**
 * MCC Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseResource
 */
export interface BaseResource {
    /**
     * 
     * @type {Date}
     * @memberof BaseResource
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the BaseResource interface.
 */
export function instanceOfBaseResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function BaseResourceFromJSON(json: any): BaseResource {
    return BaseResourceFromJSONTyped(json, false);
}

export function BaseResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
    };
}

export function BaseResourceToJSON(value?: BaseResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': (value.createdAt.toISOString()),
    };
}

