/* tslint:disable */
/* eslint-disable */
/**
 * MACH composer Cloud (MCC) Public API
 * # Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.  All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html). 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: mach@labdigital.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommitDataAllOf
 */
export interface CommitDataAllOf {
    /**
     * 
     * @type {Date}
     * @memberof CommitDataAllOf
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the CommitDataAllOf interface.
 */
export function instanceOfCommitDataAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CommitDataAllOfFromJSON(json: any): CommitDataAllOf {
    return CommitDataAllOfFromJSONTyped(json, false);
}

export function CommitDataAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitDataAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
    };
}

export function CommitDataAllOfToJSON(value?: CommitDataAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
    };
}

