/* tslint:disable */
/* eslint-disable */
/**
 * MCC Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComponentDraft
 */
export interface ComponentDraft {
    /**
     * 
     * @type {string}
     * @memberof ComponentDraft
     */
    key: string;
}

/**
 * Check if a given object implements the ComponentDraft interface.
 */
export function instanceOfComponentDraft(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function ComponentDraftFromJSON(json: any): ComponentDraft {
    return ComponentDraftFromJSONTyped(json, false);
}

export function ComponentDraftFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComponentDraft {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
    };
}

export function ComponentDraftToJSON(value?: ComponentDraft | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
    };
}

