/* tslint:disable */
/* eslint-disable */
/**
 * MCC Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ComponentVersion } from './ComponentVersion';
import {
    ComponentVersionFromJSON,
    ComponentVersionFromJSONTyped,
    ComponentVersionToJSON,
} from './ComponentVersion';

/**
 * 
 * @export
 * @interface ComponentVersionPaginatorAllOf
 */
export interface ComponentVersionPaginatorAllOf {
    /**
     * 
     * @type {Array<ComponentVersion>}
     * @memberof ComponentVersionPaginatorAllOf
     */
    results?: Array<ComponentVersion>;
}

/**
 * Check if a given object implements the ComponentVersionPaginatorAllOf interface.
 */
export function instanceOfComponentVersionPaginatorAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ComponentVersionPaginatorAllOfFromJSON(json: any): ComponentVersionPaginatorAllOf {
    return ComponentVersionPaginatorAllOfFromJSONTyped(json, false);
}

export function ComponentVersionPaginatorAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComponentVersionPaginatorAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(ComponentVersionFromJSON)),
    };
}

export function ComponentVersionPaginatorAllOfToJSON(value?: ComponentVersionPaginatorAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(ComponentVersionToJSON)),
    };
}

