/* tslint:disable */
/* eslint-disable */
/**
 * MCC Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComponentAllOf
 */
export interface ComponentAllOf {
    /**
     * key of the component
     * @type {string}
     * @memberof ComponentAllOf
     */
    key?: string;
}

/**
 * Check if a given object implements the ComponentAllOf interface.
 */
export function instanceOfComponentAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ComponentAllOfFromJSON(json: any): ComponentAllOf {
    return ComponentAllOfFromJSONTyped(json, false);
}

export function ComponentAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComponentAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
    };
}

export function ComponentAllOfToJSON(value?: ComponentAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
    };
}

