/* tslint:disable */
/* eslint-disable */
/**
 * MACH composer Cloud (MCC) Public API
 * # Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.  All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html). 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: mach@labdigital.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorUnauthorized
 */
export interface ErrorUnauthorized {
    /**
     * 
     * @type {string}
     * @memberof ErrorUnauthorized
     */
    message?: string;
}

/**
 * Check if a given object implements the ErrorUnauthorized interface.
 */
export function instanceOfErrorUnauthorized(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ErrorUnauthorizedFromJSON(json: any): ErrorUnauthorized {
    return ErrorUnauthorizedFromJSONTyped(json, false);
}

export function ErrorUnauthorizedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorUnauthorized {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ErrorUnauthorizedToJSON(value?: ErrorUnauthorized | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

