/* tslint:disable */
/* eslint-disable */
/**
 * MACH composer Cloud (MCC) Public API
 * # Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.  All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html). 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: mach@labdigital.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorForbidden
 */
export interface ErrorForbidden {
    /**
     * 
     * @type {number}
     * @memberof ErrorForbidden
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorForbidden
     */
    summary?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorForbidden
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorForbidden
     */
    message?: string;
}

/**
 * Check if a given object implements the ErrorForbidden interface.
 */
export function instanceOfErrorForbidden(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ErrorForbiddenFromJSON(json: any): ErrorForbidden {
    return ErrorForbiddenFromJSONTyped(json, false);
}

export function ErrorForbiddenFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorForbidden {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'summary': !exists(json, 'summary') ? undefined : json['summary'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ErrorForbiddenToJSON(value?: ErrorForbidden | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'summary': value.summary,
        'description': value.description,
        'message': value.message,
    };
}

