/* tslint:disable */
/* eslint-disable */
/**
 * MACH composer Cloud (MCC) Public API
 * # Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.  All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html). 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: mach@labdigital.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MyAccountInformation200Response
 */
export interface MyAccountInformation200Response {
    /**
     * 
     * @type {Date}
     * @memberof MyAccountInformation200Response
     */
    createdAt?: Date;
    /**
     * Name of the user
     * @type {string}
     * @memberof MyAccountInformation200Response
     */
    name?: string;
    /**
     * E-mail address of the user
     * @type {string}
     * @memberof MyAccountInformation200Response
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof MyAccountInformation200Response
     */
    avatarUrl?: string;
}

/**
 * Check if a given object implements the MyAccountInformation200Response interface.
 */
export function instanceOfMyAccountInformation200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MyAccountInformation200ResponseFromJSON(json: any): MyAccountInformation200Response {
    return MyAccountInformation200ResponseFromJSONTyped(json, false);
}

export function MyAccountInformation200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyAccountInformation200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'avatarUrl': !exists(json, 'avatar_url') ? undefined : json['avatar_url'],
    };
}

export function MyAccountInformation200ResponseToJSON(value?: MyAccountInformation200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'name': value.name,
        'email': value.email,
        'avatar_url': value.avatarUrl,
    };
}

