/* tslint:disable */
/* eslint-disable */
/**
 * MACH composer Cloud (MCC) Public API
 * # Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.  All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html). 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: mach@labdigital.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationUserInviteDraft
 */
export interface OrganizationUserInviteDraft {
    /**
     * E-mail address of the user
     * @type {string}
     * @memberof OrganizationUserInviteDraft
     */
    email: string;
    /**
     * Key of the project to invite user to
     * @type {string}
     * @memberof OrganizationUserInviteDraft
     */
    projectKey?: string;
    /**
     * Role for the user
     * @type {string}
     * @memberof OrganizationUserInviteDraft
     */
    role?: OrganizationUserInviteDraftRoleEnum;
}


/**
 * @export
 */
export const OrganizationUserInviteDraftRoleEnum = {
    Owner: 'owner',
    Member: 'member',
    Viewer: 'viewer'
} as const;
export type OrganizationUserInviteDraftRoleEnum = typeof OrganizationUserInviteDraftRoleEnum[keyof typeof OrganizationUserInviteDraftRoleEnum];


/**
 * Check if a given object implements the OrganizationUserInviteDraft interface.
 */
export function instanceOfOrganizationUserInviteDraft(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function OrganizationUserInviteDraftFromJSON(json: any): OrganizationUserInviteDraft {
    return OrganizationUserInviteDraftFromJSONTyped(json, false);
}

export function OrganizationUserInviteDraftFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationUserInviteDraft {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'projectKey': !exists(json, 'project_key') ? undefined : json['project_key'],
        'role': !exists(json, 'role') ? undefined : json['role'],
    };
}

export function OrganizationUserInviteDraftToJSON(value?: OrganizationUserInviteDraft | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'project_key': value.projectKey,
        'role': value.role,
    };
}

