/* tslint:disable */
/* eslint-disable */
/**
 * MCC Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationUserInvite401Response
 */
export interface OrganizationUserInvite401Response {
    /**
     * 
     * @type {string}
     * @memberof OrganizationUserInvite401Response
     */
    message: string;
}

/**
 * Check if a given object implements the OrganizationUserInvite401Response interface.
 */
export function instanceOfOrganizationUserInvite401Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function OrganizationUserInvite401ResponseFromJSON(json: any): OrganizationUserInvite401Response {
    return OrganizationUserInvite401ResponseFromJSONTyped(json, false);
}

export function OrganizationUserInvite401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationUserInvite401Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function OrganizationUserInvite401ResponseToJSON(value?: OrganizationUserInvite401Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

