/* tslint:disable */
/* eslint-disable */
/**
 * MCC Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationUserInvite
 */
export interface OrganizationUserInvite {
    /**
     * E-mail address of the user
     * @type {string}
     * @memberof OrganizationUserInvite
     */
    email: string;
}

/**
 * Check if a given object implements the OrganizationUserInvite interface.
 */
export function instanceOfOrganizationUserInvite(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function OrganizationUserInviteFromJSON(json: any): OrganizationUserInvite {
    return OrganizationUserInviteFromJSONTyped(json, false);
}

export function OrganizationUserInviteFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationUserInvite {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function OrganizationUserInviteToJSON(value?: OrganizationUserInvite | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

