/* tslint:disable */
/* eslint-disable */
/**
 * MCC Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationUserInviteDraft
 */
export interface OrganizationUserInviteDraft {
    /**
     * E-mail address of the user
     * @type {string}
     * @memberof OrganizationUserInviteDraft
     */
    email: string;
}

/**
 * Check if a given object implements the OrganizationUserInviteDraft interface.
 */
export function instanceOfOrganizationUserInviteDraft(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function OrganizationUserInviteDraftFromJSON(json: any): OrganizationUserInviteDraft {
    return OrganizationUserInviteDraftFromJSONTyped(json, false);
}

export function OrganizationUserInviteDraftFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationUserInviteDraft {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function OrganizationUserInviteDraftToJSON(value?: OrganizationUserInviteDraft | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

