/* tslint:disable */
/* eslint-disable */
/**
 * MCC Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Organization } from './Organization';
import {
    OrganizationFromJSON,
    OrganizationFromJSONTyped,
    OrganizationToJSON,
} from './Organization';

/**
 * 
 * @export
 * @interface OrganizationPaginatorAllOf
 */
export interface OrganizationPaginatorAllOf {
    /**
     * 
     * @type {Array<Organization>}
     * @memberof OrganizationPaginatorAllOf
     */
    results?: Array<Organization>;
}

/**
 * Check if a given object implements the OrganizationPaginatorAllOf interface.
 */
export function instanceOfOrganizationPaginatorAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrganizationPaginatorAllOfFromJSON(json: any): OrganizationPaginatorAllOf {
    return OrganizationPaginatorAllOfFromJSONTyped(json, false);
}

export function OrganizationPaginatorAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationPaginatorAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(OrganizationFromJSON)),
    };
}

export function OrganizationPaginatorAllOfToJSON(value?: OrganizationPaginatorAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(OrganizationToJSON)),
    };
}

