/* tslint:disable */
/* eslint-disable */
/**
 * MCC Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationAllOf
 */
export interface OrganizationAllOf {
    /**
     * The organization key (must be unique)
     * @type {string}
     * @memberof OrganizationAllOf
     */
    key: string;
    /**
     * The name of the organization
     * @type {string}
     * @memberof OrganizationAllOf
     */
    name: string;
}

/**
 * Check if a given object implements the OrganizationAllOf interface.
 */
export function instanceOfOrganizationAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function OrganizationAllOfFromJSON(json: any): OrganizationAllOf {
    return OrganizationAllOfFromJSONTyped(json, false);
}

export function OrganizationAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'name': json['name'],
    };
}

export function OrganizationAllOfToJSON(value?: OrganizationAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'name': value.name,
    };
}

