/* tslint:disable */
/* eslint-disable */
/**
 * MACH composer Cloud (MCC) Public API
 * # Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.  All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html). 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: mach@labdigital.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrganizationUserInviteDataOrganization } from './OrganizationUserInviteDataOrganization';
import {
    OrganizationUserInviteDataOrganizationFromJSON,
    OrganizationUserInviteDataOrganizationFromJSONTyped,
    OrganizationUserInviteDataOrganizationToJSON,
} from './OrganizationUserInviteDataOrganization';

/**
 * 
 * @export
 * @interface OrganizationUserInviteData
 */
export interface OrganizationUserInviteData {
    /**
     * 
     * @type {string}
     * @memberof OrganizationUserInviteData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUserInviteData
     */
    createdBy: string;
    /**
     * 
     * @type {OrganizationUserInviteDataOrganization}
     * @memberof OrganizationUserInviteData
     */
    organization: OrganizationUserInviteDataOrganization;
}

/**
 * Check if a given object implements the OrganizationUserInviteData interface.
 */
export function instanceOfOrganizationUserInviteData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "createdBy" in value;
    isInstance = isInstance && "organization" in value;

    return isInstance;
}

export function OrganizationUserInviteDataFromJSON(json: any): OrganizationUserInviteData {
    return OrganizationUserInviteDataFromJSONTyped(json, false);
}

export function OrganizationUserInviteDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationUserInviteData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdBy': json['created_by'],
        'organization': OrganizationUserInviteDataOrganizationFromJSON(json['organization']),
    };
}

export function OrganizationUserInviteDataToJSON(value?: OrganizationUserInviteData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'created_by': value.createdBy,
        'organization': OrganizationUserInviteDataOrganizationToJSON(value.organization),
    };
}

