/* tslint:disable */
/* eslint-disable */
/**
 * MCC Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrganizationUser } from './OrganizationUser';
import {
    OrganizationUserFromJSON,
    OrganizationUserFromJSONTyped,
    OrganizationUserToJSON,
} from './OrganizationUser';

/**
 * 
 * @export
 * @interface OrganizationUserPaginatorAllOf
 */
export interface OrganizationUserPaginatorAllOf {
    /**
     * 
     * @type {Array<OrganizationUser>}
     * @memberof OrganizationUserPaginatorAllOf
     */
    results?: Array<OrganizationUser>;
}

/**
 * Check if a given object implements the OrganizationUserPaginatorAllOf interface.
 */
export function instanceOfOrganizationUserPaginatorAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrganizationUserPaginatorAllOfFromJSON(json: any): OrganizationUserPaginatorAllOf {
    return OrganizationUserPaginatorAllOfFromJSONTyped(json, false);
}

export function OrganizationUserPaginatorAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationUserPaginatorAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(OrganizationUserFromJSON)),
    };
}

export function OrganizationUserPaginatorAllOfToJSON(value?: OrganizationUserPaginatorAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(OrganizationUserToJSON)),
    };
}

