/* tslint:disable */
/* eslint-disable */
/**
 * MCC Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Paginator
 */
export interface Paginator {
    /**
     * 
     * @type {number}
     * @memberof Paginator
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof Paginator
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof Paginator
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof Paginator
     */
    limit: number;
}

/**
 * Check if a given object implements the Paginator interface.
 */
export function instanceOfPaginator(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "total" in value;
    isInstance = isInstance && "offset" in value;
    isInstance = isInstance && "limit" in value;

    return isInstance;
}

export function PaginatorFromJSON(json: any): Paginator {
    return PaginatorFromJSONTyped(json, false);
}

export function PaginatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Paginator {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'total': json['total'],
        'offset': json['offset'],
        'limit': json['limit'],
    };
}

export function PaginatorToJSON(value?: Paginator | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'total': value.total,
        'offset': value.offset,
        'limit': value.limit,
    };
}

