/* tslint:disable */
/* eslint-disable */
/**
 * MACH composer Cloud (MCC) Public API
 * # Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.  All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html). 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: mach@labdigital.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    JSONPatchRequestAddReplaceTest,
    instanceOfJSONPatchRequestAddReplaceTest,
    JSONPatchRequestAddReplaceTestFromJSON,
    JSONPatchRequestAddReplaceTestFromJSONTyped,
    JSONPatchRequestAddReplaceTestToJSON,
} from './JSONPatchRequestAddReplaceTest';
import {
    JSONPatchRequestMoveCopy,
    instanceOfJSONPatchRequestMoveCopy,
    JSONPatchRequestMoveCopyFromJSON,
    JSONPatchRequestMoveCopyFromJSONTyped,
    JSONPatchRequestMoveCopyToJSON,
} from './JSONPatchRequestMoveCopy';
import {
    JSONPatchRequestRemove,
    instanceOfJSONPatchRequestRemove,
    JSONPatchRequestRemoveFromJSON,
    JSONPatchRequestRemoveFromJSONTyped,
    JSONPatchRequestRemoveToJSON,
} from './JSONPatchRequestRemove';

/**
 * @type PatchRequestInner
 * 
 * @export
 */
export type PatchRequestInner = JSONPatchRequestAddReplaceTest | JSONPatchRequestMoveCopy | JSONPatchRequestRemove;

export function PatchRequestInnerFromJSON(json: any): PatchRequestInner {
    return PatchRequestInnerFromJSONTyped(json, false);
}

export function PatchRequestInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchRequestInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...JSONPatchRequestAddReplaceTestFromJSONTyped(json, true), ...JSONPatchRequestMoveCopyFromJSONTyped(json, true), ...JSONPatchRequestRemoveFromJSONTyped(json, true) };
}

export function PatchRequestInnerToJSON(value?: PatchRequestInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfJSONPatchRequestAddReplaceTest(value)) {
        return JSONPatchRequestAddReplaceTestToJSON(value as JSONPatchRequestAddReplaceTest);
    }
    if (instanceOfJSONPatchRequestMoveCopy(value)) {
        return JSONPatchRequestMoveCopyToJSON(value as JSONPatchRequestMoveCopy);
    }
    if (instanceOfJSONPatchRequestRemove(value)) {
        return JSONPatchRequestRemoveToJSON(value as JSONPatchRequestRemove);
    }

    return {};
}

